[package]
name = "rcchat_bridge"
version = "0.1.0"
authors = ["Ed Cragg <drq.11235@gmail.com>"]
edition = "2018"
description = "rcchat bridge"

[dependencies]
docopt = "1.1.0"
irc = "0.14.0"
xmpp = "0.3.0"
slack = "0.23.0"
serenity = "0.8.6"
tokio = "1.3.0"
serde = "1.0.110"
#discord = "0.8.0"
