[package]
name = "roffl_bridge"
version = "0.1.0"
authors = ["Ed Cragg <drq.11235@gmail.com>"]
edition = "2018"
description = "roffl bridge"

[dependencies]
docopt = "1.1.0"
irc = "0.13.6"
xmpp = "0.3.0"
slack = "0.23.0"
serenity = "0.8.3"
tokio = "0.2.18"
#discord = "0.8.0"
